title: "phat nguyen"
description: "Daily blog"
lang: vi
timezone: Asia/Ho_Chi_Minh

url: "https://phat8507.github.io"
baseurl: ""   # <-- repo project thì đổi thành "/TEN-REPO"

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown
plugins:
  - jekyl
